### ISSUE TITLE
offer to package for debian/ubuntu

### ISSUE THREAD

**Issue by ItzSwirlz** [itsmattkc/SIEdit#1]
Hey Matt, I'm willing to package this for Debian-based systems if you wished (when time comes). Would you be interested in that as this lib continues? I imagine it is for Lego Island but.. idk I guess if you want to test Wine support. Lego Island iirc can run on Linux w/ wine

**Comment by WinFan3672** [comment]
Please do so. I don't see any issue with doing this from the perspective of the author of a project. Packaging under Linux can be complex, so support is always welcome. 

(At least just send me the .deb)

**Comment by itsmattkc** [comment]
Packaging is up to you. We probably won't officially support Debian/Ubuntu in this repository, but if you'd like to create a package yourself, go for it.
