### ISSUE TITLE
Failed to write file.

### ISSUE THREAD

**Issue by techsideofficial** [itsmattkc/SIEdit#11]
<img width="253" alt="image" src="https://github.com/itsmattkc/SIEdit/assets/68258126/adeb0a87-2ec0-4f68-90e9-7eabfffe94af">

**Comment by itsmattkc** [comment]
You need to provide a lot more information about the circumstances this error is occurring in, simply sending an error message doesn't tell us much.

This is most likely a file/folder permissions issue on your end, but I couldn't say for sure with the limited information you've provided.

**Comment by techsideofficial** [comment]
> You need to provide a lot more information about the circumstances this error is occurring in, simply sending an error message doesn't tell us much.
> 
> This is most likely a file/folder permissions issue on your end, but I couldn't say for sure with the limited information you've provided.

Fixed it, just wouldn't export 2 files at once. I have to manually export the smk and wav separately.
