### ISSUE TITLE
Encountered radio error in-game with the prebuilt SIEdit; struggling to build manually to try changing extra data

### ISSUE THREAD

**Issue by LegoLoco7** [itsmattkc/SIEdit#5]
This tool works great, but I noticed the prebuilt version of it doesn't have certain features, and uses Windows' default UI, unlike in the README.MD screenshot and footage in the LEGO Island decomp part 2 video. Furthermore, I had an issue with editing JUKEBOX.SI that I had previously when using the .NET release of LEGO Island Rebuilder where the radio would break when playing music that would normally loop, so they loop in the radio anyway. This, to my knowledge, does not normally happen in LEGO Island (hence why I said it broke), so I'd wondered if editing the "extra" data could help find a fix. I tried building SIEdit from source based on the few instructions here, but obtaining Qt for CMake turned out to be way more complicated than it should be. On Linux, you'd just have to run a few commands, but on Windows, you have to compile Qt from source manually or use the rather confusing installer. All I got from the installer is a bunch of EXEs/DLLs in a folder; with no Qt5Config.cmake file in sight. Downloading just the source for Qt5 didn't work, either. There are CMake files, but no config. I'm really stumped.

**Comment by itsmattkc** [comment]
Hmm I think the script we use to upload a GitHub release may have broken within the past few weeks. I'll file an issue with them. In the mean time, I've updated the release manually to the latest version, there shouldn't be any missing features now. See if there's still any issue with JUKEBOX.SI.

> uses Windows' default UI, unlike in the README.MD screenshot and footage in the LEGO Island decomp part 2 video

The theme in the screenshot is just KDE's default theme. SIEdit has no theme of its own and will use whatever is native on your system.

> On Linux, you'd just have to run a few commands, but on Windows, you have to compile Qt from source manually or use the rather confusing installer. All I got from the installer is a bunch of EXEs/DLLs in a folder; with no Qt5Config.cmake file in sight. Downloading just the source for Qt5 didn't work, either. There are CMake files, but no config. I'm really stumped.

This is just the reality of C++ on Windows I'm afraid. It can be done, but everything is generally a lot harder.

**Comment by LegoLoco7** [comment]
>In the mean time, I've updated the release manually to the latest version

Thanks, this saves a lot of time.
>The theme in the screenshot is just KDE's default theme.

Ah, I hadn't seen it before, so I didn't know that. I also couldn't quite remember what Qt actually did based on other apps I've seen with it.
>This is just the reality of C++ on Windows I'm afraid. It can be done, but everything is generally a lot harder.

Understandable. I'd really like to install a Linux distro at some point (since it's generally better), but I have compatibility concerns; especially with a lot of the older games I play that I just barely can get working with Windows. I'd probably try dual-booting for this reason. But, anyway...
>See if there's still any issue with JUKEBOX.SI.

Okay, so it turns out this is normal LEGO Island behavior. I restored the original JUKEBOX.SI and ran LEGO Island without Rebuilder, and it still loops Happy Roaming (aka CentralRoads_Music/lego_3.wav) whenever it plays on the radio. It may be impossible to fix this as of now.
