### ISSUE TITLE
Newest build crashes when opening files.

### ISSUE THREAD

**Issue by A-6-hawk** [itsmattkc/SIEdit#6]
Title says it all, every time i try to open an SI with "artifact" the program crashes. Tried it on two systems.

**Comment by Andy4169** [comment]
same

**Comment by Andy4169** [comment]
i tried using ubuntu and wine and this is the error i got
"Unhandled exception: page fault on read access to 0x0000000000000000 in 64-bit code (0x00000007ea2923).
Register dump:
 rip:0000000007ea2923 rsp:000000000011a4f0 rbp:000000000011a5a0 eflags:00010256 (  R- --  I  Z-A-P- )
 rax:000000000011a650 rbx:0000000000000000 rcx:000000000011a650 rdx:0000000000000000
 rsi:000000000011a650 rdi:000000000011a650  r8:0000000000000000  r9:0000000000000000 r10:0000000000000000
 r11:0000000000000202 r12:0000000000000000 r13:0000000008400ca0 r14:0000000000000000 r15:000000000011a578
Stack dump:
0x0000000011a4f0:  0000000000000000 000000031bf14aca
0x0000000011a500:  0000000000000000 0000000007ea21f0
0x0000000011a510:  000000000011a650 000000000011ae01
0x0000000011a520:  000000000011a578 000000000011ae00
0x0000000011a530:  0000000000000000 000000000011a650
0x0000000011a540:  00000000083103a0 0000000007ea59b0
0x0000000011a550:  000000000011a650 0000000008310478
0x0000000011a560:  0000000000000000 0000000000000000
0x0000000011a570:  000000000011a6e0 0000000000000000
0x0000000011a580:  0000000000000000 0000000000000000
0x0000000011a590:  000000000000000f 000074ba57e731be
0x0000000011a5a0:  00000000000001fd 000000000011fc20
Backtrace:
=>0 0x00000007ea2923 in libweaver (+0x2923) (0x0000000011a5a0)
  1 0x00000007ea59b0 in libweaver (+0x59b0) (0x0000000011a5a0)
  2 0x00000007ea499c in libweaver (+0x499c) (0x0000000011a6e0)
  3 0x00000007ea51f5 in libweaver (+0x51f5) (0x0000000011a8e0)
  4 0x00000007ea51f5 in libweaver (+0x51f5) (0x0000000011aae0)
  5 0x00000007ea51f5 in libweaver (+0x51f5) (0x0000000011ace0)
  6 0x00000007ea44f2 in libweaver (+0x44f2) (0x0000000011b020)
  7 0x00000140009436 in si-edit (+0x9436) (0x0000000011b020)
  8 0x000001400092fe in si-edit (+0x92fe) (0x0000000011b020)
  9 0x00000000ff1d49 in qt5core (+0x1f1d49) (0x0000000011b020)
  10 0x00000180005dcf in qt5widgets (+0x5dcf) (0x000000083bdbd0)
  11 0x0000018015b4d8 in qt5widgets (+0x15b4d8) (0x000000083bdbd0)
  12 0x0000018015b2b3 in qt5widgets (+0x15b2b3) (0x000000083bdbd0)
  13 0x00000180160a91 in qt5widgets (+0x160a91) (0x0000000011b298)
  14 0x000001800379b2 in qt5widgets (+0x379b2) (0x0000000011b298)
  15 0x0000018015ca77 in qt5widgets (+0x15ca77) (0x0000000834f520)
  16 0x00000180014990 in qt5widgets (+0x14990) (0x0000000834f520)
  17 0x000001800128b0 in qt5widgets (+0x128b0) (0x0000000011b480)
  18 0x00000000fd2aca in qt5core (+0x1d2aca) (0x0000000011bcc0)
  19 0x00000180015b95 in qt5widgets (+0x15b95) (0x000000ffffffff)
  20 0x0000018005fdca in qt5widgets (+0x5fdca) (0x0000000011baf0)
  21 0x0000018005e38e in qt5widgets (+0x5e38e) (0x0000000834f520)
  22 0x00000180014990 in qt5widgets (+0x14990) (0x0000000834f520)
  23 0x00000180013a13 in qt5widgets (+0x13a13) (0x0000000011bf80)
  24 0x00000000fd2aca in qt5core (+0x1d2aca) (0x0000000011c730)
  25 0x000000007832b6 in qt5gui (+0x432b6) (0x0000000011c530)
  26 0x0000000076ecb0 in qt5gui (+0x2ecb0) (0x00000000dae148)
  27 0x0000000101ba5a in qt5core (+0x21ba5a) (0x0000000011ca10)
  28 0x000000098f2dd9 in qwindows (+0x62dd9) (0x0000000011faf0)
  29 0x00000000fcef2c in qt5core (+0x1cef2c) (0x0000000011faf0)
  30 0x00000000fd1a94 in qt5core (+0x1d1a94) (0x0000000011fc30)
  31 0x00000140006fdc in si-edit (+0x6fdc) (0x0000000011fc30)
  32 0x0000014000cba7 in si-edit (+0xcba7) (0000000000000000)
  33 0x0000014000c176 in si-edit (+0xc176) (0000000000000000)
  34 0x0000007b627e59 in kernel32 (+0x27e59) (0000000000000000)
  35 0x0000017005dba8 in ntdll (+0x5dba8) (0000000000000000)
0x00000007ea2923 libweaver+0x2923: cmpb	%bl,(%rdx,%r14,1)
Modules:
Module	Address					Debug info	Name (181 modules)
PE	0000000000740000-0000000000dfb000	Export          qt5gui
PE	0000000000e00000-00000000013c6000	Export          qt5core
PE	00000000013d0000-00000000015f6000	Deferred        rpcrt4
PE	0000000001600000-00000000016b9000	Deferred        qt5multimedia
PE	00000000016c0000-000000000180b000	Deferred        qt5network
PE	0000000001810000-0000000001ae2000	Deferred        crypt32
PE	0000000001af0000-0000000001dc6000	Deferred        avutil-56
PE	0000000001dd0000-0000000006ec8000	Deferred        avcodec-58
PE	0000000006ed0000-0000000006fa9000	Deferred        swresample-3
PE	0000000006fb0000-0000000007df4000	Deferred        avformat-58
PE	0000000007e00000-0000000007e9c000	Deferred        swscale-5
PE	0000000007ea0000-0000000007eb3000	Export          libweaver
PE	0000000009890000-00000000099fd000	Export          qwindows
PE	0000000009a00000-0000000009a26000	Deferred        qwindowsvistastyle
PE	0000000009a30000-0000000009a3d000	Deferred        qgif
PE	0000000009a40000-0000000009a4f000	Deferred        qicns
PE	0000000009a50000-0000000009a5d000	Deferred        qico
PE	0000000009a60000-0000000009acb000	Deferred        qjpeg
PE	0000000009ad0000-0000000009adc000	Deferred        qsvg
PE	0000000009ae0000-0000000009b34000	Deferred        qt5svg
PE	0000000009b40000-0000000009b4c000	Deferred        qtga
PE	0000000009b50000-0000000009bb3000	Deferred        qtiff
PE	0000000009bc0000-0000000009bcb000	Deferred        qwbmp
PE	0000000009bd0000-0000000009c53000	Deferred        qwebp
PE	000000007a800000-000000007ac8f000	Deferred        opengl32
PE	000000007b000000-000000007b515000	Deferred        kernelbase
PE	000000007b600000-000000007b75b000	Dwarf-5         kernel32
ELF	000000007d000000-000000007d005000	Deferred        <wine-loader>
PE	0000000140000000-0000000140044000	Export          si-edit
PE	0000000170000000-00000001702b5000	Dwarf-5         ntdll
PE	0000000180000000-0000000180541000	Export          qt5widgets
PE	00000001cb930000-00000001cba5c000	Deferred        dxgi
PE	00000001ce760000-00000001ce78a000	Deferred        kerberos
PE	00000001d0e20000-00000001d1254000	Deferred        oleaut32
PE	00000001d3e90000-00000001d3eaa000	Deferred        msvcp140_1
PE	00000001d4930000-00000001d49b5000	Deferred        netapi32
PE	00000001d8c90000-00000001d8d90000	Deferred        advapi32
PE	00000001dbc50000-00000001dbed6000	Deferred        dwrite
PE	00000001dc470000-00000001dc482000	Deferred        cfgmgr32
PE	00000001eaf60000-00000001eb005000	Deferred        sechost
PE	00000001ffb10000-00000001ffb42000	Deferred        rtworkq
PE	000000020b860000-000000020bd1a000	Deferred        ole32
PE	00000002169d0000-0000000216eb8000	Deferred        user32
PE	0000000222ed0000-00000002230dc000	Deferred        comdlg32
PE	0000000223d50000-0000000223df4000	Deferred        winspool
PE	0000000228280000-00000002284fd000	Deferred        msvcrt
PE	000000023bc00000-000000023c8a4000	Deferred        shell32
PE	0000000244fc0000-0000000244fe8000	Deferred        userenv
PE	0000000250cd0000-0000000250d29000	Deferred        mpr
PE	0000000251d80000-0000000251e0d000	Deferred        winex11
PE	000000025dc30000-000000025dc4e000	Deferred        version
PE	00000002605d0000-00000002605e8000	Deferred        vcruntime140
PE	0000000263650000-00000002636cc000	Deferred        propsys
PE	000000026c190000-000000026c1af000	Deferred        nsi
PE	000000026c230000-000000026c2d4000	Deferred        uxtheme
PE	000000027a8e0000-000000027aa50000	Deferred        d3d9
PE	00000002945e0000-000000029476c000	Deferred        winmm
PE	0000000296590000-00000002965d3000	Deferred        dnsapi
PE	00000002a2380000-00000002a2483000	Deferred        shlwapi
PE	00000002ac810000-00000002ac83c000	Deferred        vcruntime140_1
PE	00000002bb0a0000-00000002bb2b5000	Deferred        gdi32
PE	00000002bde30000-00000002bde7b000	Deferred        shcore
PE	00000002c73a0000-00000002c73f0000	Deferred        win32u
PE	00000002c7470000-00000002c7750000	Deferred        ucrtbase
PE	00000002ee630000-00000002ee676000	Deferred        bcrypt
PE	00000002ef230000-00000002ef24e000	Deferred        dwmapi
PE	00000002fb3c0000-00000002fb819000	Deferred        comctl32
PE	00000002fba30000-00000002fbab8000	Deferred        concrt140
PE	0000000302d10000-0000000302d27000	Deferred        msimg32
PE	000000030b860000-000000030baff000	Deferred        d3d11
PE	0000000313390000-00000003133bf000	Deferred        compstui
PE	000000031bef0000-000000031c206000	Deferred        msvcp140
PE	000000031c5d0000-000000031c72b000	Deferred        combase
PE	000000032b540000-000000032b576000	Deferred        wintab32
PE	0000000351a60000-0000000351ac6000	Deferred        msacm32
PE	0000000367600000-0000000368980000	Deferred        wined3d
PE	000000036d860000-000000036d9fe000	Deferred        setupapi
PE	0000000370f70000-0000000370ffe000	Deferred        ws2_32
PE	0000000393730000-0000000393784000	Deferred        imm32
PE	0000000393e70000-0000000393ee1000	Deferred        explorerframe
PE	0000000394ba0000-0000000394bcc000	Deferred        wtsapi32
PE	00000003982d0000-000000039835d000	Deferred        iphlpapi
PE	00000003afef0000-00000003aff83000	Deferred        secur32
PE	00000003bb450000-00000003bb604000	Deferred        mfplat
ELF	00007fe3ad20b000-00007fe3ad349000	Deferred        libgcrypt.so.20
ELF	00007fe3ad349000-00007fe3ad410000	Deferred        libsystemd.so.0
ELF	00007fe3ad410000-00007fe3ad4ae000	Deferred        libcups.so.2
ELF	00007fe3ae000000-00007fe3af998000	Deferred        nouveau_dri.so
ELF	00007fe3af9da000-00007fe3afa00000	Deferred        libgpg-error.so.0
ELF	00007fe3afa00000-00007fe3b161e000	Deferred        libicudata.so.70
ELF	00007fe3b1623000-00007fe3b181e000	Deferred        libicuuc.so.70
ELF	00007fe3b181e000-00007fe3b1a00000	Deferred        libxml2.so.2
ELF	00007fe3b1a00000-00007fe3b89f2000	Deferred        libllvm-15.so.1
ELF	00007fe3b89f4000-00007fe3b89ff000	Deferred        libcap.so.2
ELF	00007fe3b942c000-00007fe3b944c000	Deferred        liblz4.so.1
ELF	00007fe3b944c000-00007fe3b949a000	Deferred        libdbus-1.so.3
ELF	00007fe3b949a000-00007fe3b94ae000	Deferred        libavahi-client.so.3
ELF	00007fe3b94ae000-00007fe3b94bc000	Deferred        libavahi-common.so.3
ELF	00007fe3b9cb5000-00007fe3b9cc0000	Deferred        libdrm_nouveau.so.2
ELF	00007fe3b9cc0000-00007fe3b9ccc000	Deferred        libdrm_amdgpu.so.1
ELF	00007fe3b9ccc000-00007fe3b9cea000	Deferred        libelf.so.1
ELF	00007fe3b9cea000-00007fe3b9cf9000	Deferred        libdrm_radeon.so.1
ELF	00007fe3b9cf9000-00007fe3b9d09000	Deferred        libsensors.so.5
ELF	00007fe3b9d09000-00007fe3b9dd8000	Deferred        libzstd.so.1
ELF	00007fe3b9dd8000-00007fe3b9df5000	Deferred        libxcb-glx.so.0
ELF	00007fe3b9df5000-00007fe3b9e67000	Deferred        libglx_mesa.so.0
ELF	00007fe3b9e67000-00007fe3b9f1f000	Deferred        libgldispatch.so.0
ELF	00007fe3b9f1f000-00007fe3b9f51000	Deferred        libtinfo.so.6
ELF	00007fe3b9f54000-00007fe3b9f5e000	Deferred        libxcb-xfixes.so.0
ELF	00007fe3b9f5e000-00007fe3b9f99000	Deferred        libglapi.so.0
ELF	00007fe3b9f99000-00007fe3ba020000	Deferred        libgl.so.1
ELF	00007fe3ba062000-00007fe3ba06c000	Deferred        libxcb-sync.so.1
ELF	00007fe3ba06c000-00007fe3ba082000	Deferred        libdrm.so.2
ELF	00007fe3ba082000-00007fe3ba0bc000	Deferred        libedit.so.2
ELF	00007fe3ba0bc000-00007fe3ba0dc000	Deferred        libgcc_s.so.1
ELF	00007fe3ba0de000-00007fe3ba0e4000	Deferred        winspool.so
ELF	00007fe3ba0e4000-00007fe3ba0e9000	Deferred        libxcb-present.so.0
ELF	00007fe3ba0e9000-00007fe3ba0f0000	Deferred        libxcb-dri3.so.0
ELF	00007fe3ba0f0000-00007fe3ba124000	Deferred        libglx.so.0
ELF	00007fe3ba168000-00007fe3ba1d6000	Deferred        libvulkan.so.1
ELF	00007fe3ba1da000-00007fe3ba1df000	Deferred        libxshmfence.so.1
ELF	00007fe3ba1df000-00007fe3ba1e4000	Deferred        libxcb-shm.so.0
ELF	00007fe3ba1eb000-00007fe3ba23f000	Deferred        libgssapi_krb5.so.2
ELF	00007fe3ba23f000-00007fe3ba253000	Deferred        libresolv.so.2
ELF	00007fe3ba253000-00007fe3ba25a000	Deferred        libkeyutils.so.1
ELF	00007fe3ba25a000-00007fe3ba268000	Deferred        libkrb5support.so.0
ELF	00007fe3ba268000-00007fe3ba297000	Deferred        libk5crypto.so.3
ELF	00007fe3ba297000-00007fe3ba362000	Deferred        libkrb5.so.3
ELF	00007fe3ba365000-00007fe3ba36c000	Deferred        libxcb-dri2.so.0
ELF	00007fe3ba36c000-00007fe3ba371000	Deferred        libx11-xcb.so.1
ELF	00007fe3ba371000-00007fe3ba377000	Deferred        dwrite.so
ELF	00007fe3ba377000-00007fe3ba37f000	Deferred        kerberos.so
ELF	00007fe3ba37f000-00007fe3ba38c000	Deferred        libffi.so.8
ELF	00007fe3ba38c000-00007fe3ba40e000	Deferred        libgmp.so.10
ELF	00007fe3ba40e000-00007fe3ba456000	Deferred        libhogweed.so.6
ELF	00007fe3ba456000-00007fe3ba49c000	Deferred        libnettle.so.8
ELF	00007fe3ba49c000-00007fe3ba4b4000	Deferred        libtasn1.so.6
ELF	00007fe3ba4b4000-00007fe3ba65e000	Deferred        libunistring.so.2
ELF	00007fe3ba65e000-00007fe3ba67f000	Deferred        libidn2.so.0
ELF	00007fe3ba67f000-00007fe3ba7ba000	Deferred        libp11-kit.so.0
ELF	00007fe3ba7ba000-00007fe3ba9a5000	Deferred        libgnutls.so.30
ELF	00007fe3ba9a5000-00007fe3ba9ab000	Deferred        libcom_err.so.2
ELF	00007fe3ba9ab000-00007fe3ba9b4000	Deferred        secur32.so
ELF	00007fe3ba9b4000-00007fe3ba9ba000	Deferred        crypt32.so
ELF	00007fe3ba9ba000-00007fe3ba9c5000	Deferred        bcrypt.so
ELF	00007fe3baa0b000-00007fe3baa13000	Deferred        libxfixes.so.3
ELF	00007fe3baa13000-00007fe3baa1f000	Deferred        libxcursor.so.1
ELF	00007fe3baa1f000-00007fe3baa33000	Deferred        libxi.so.6
ELF	00007fe3baa33000-00007fe3baa38000	Deferred        libxcomposite.so.1
ELF	00007fe3baa38000-00007fe3baa45000	Deferred        libxrandr.so.2
ELF	00007fe3baa45000-00007fe3baa52000	Deferred        libxrender.so.1
ELF	00007fe3baa52000-00007fe3baa59000	Deferred        libxxf86vm.so.1
ELF	00007fe3baa59000-00007fe3baa5e000	Deferred        libxinerama.so.1
ELF	00007fe3baa5e000-00007fe3baa6b000	Deferred        libmd.so.0
ELF	00007fe3baa6b000-00007fe3baa83000	Deferred        libbsd.so.0
ELF	00007fe3baa83000-00007fe3baa8b000	Deferred        libxdmcp.so.6
ELF	00007fe3baa8b000-00007fe3baa91000	Deferred        libxau.so.6
ELF	00007fe3baa91000-00007fe3baabb000	Deferred        libxcb.so.1
ELF	00007fe3baabb000-00007fe3babfb000	Deferred        libx11.so.6
ELF	00007fe3babfb000-00007fe3bac10000	Deferred        libxext.so.6
ELF	00007fe3bac11000-00007fe3bac18000	Deferred        netapi32.so
ELF	00007fe3bac18000-00007fe3bac1e000	Deferred        ws2_32.so
ELF	00007fe3bac1e000-00007fe3bac23000	Deferred        dnsapi.so
ELF	00007fe3bac25000-00007fe3bacb4000	Deferred        winex11.so
ELF	00007fe3bacb4000-00007fe3bade4000	Deferred        opengl32.so
ELF	00007fe3bae7f000-00007fe3baeb0000	Deferred        libexpat.so.1
ELF	00007fe3baeb0000-00007fe3baefa000	Deferred        libfontconfig.so.1
ELF	00007fe3baefa000-00007fe3baf1d000	Deferred        libbrotlicommon.so.1
ELF	00007fe3baf1d000-00007fe3bafe5000	Deferred        libfreetype.so.6
ELF	00007fe3bafe5000-00007fe3bb0cc000	Deferred        libm.so.6
ELF	00007fe3bb0cc000-00007fe3bb28a000	Deferred        win32u.so
ELF	00007fe3bb58a000-00007fe3bb700000	Dwarf           libwine.so.1
ELF	00007fe3bc5f2000-00007fe3bc600000	Deferred        libbrotlidec.so.1
ELF	00007fe3bc600000-00007fe3bc828000	Deferred        libc.so.6
ELF	00007fe3bc82c000-00007fe3bc835000	Deferred        libuuid.so.1
ELF	00007fe3bc835000-00007fe3bc851000	Deferred        libz.so.1
ELF	00007fe3bc851000-00007fe3bc88c000	Deferred        libpng16.so.16
ELF	00007fe3bc88c000-00007fe3bc8b7000	Deferred        liblzma.so.5
ELF	00007fe3bc8b7000-00007fe3bc8d2000	Deferred        libunwind.so.8
ELF	00007fe3bc8d2000-00007fe3bc995000	Deferred        ntdll.so
ELF	00007fe3bc9af000-00007fe3bc9eb000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	00000088    0     wine_rpcrt4_io
	000000a0    0     wine_rpcrt4_io
	000000d4    0     wine_rpcrt4_io
	000000fc    0     wine_rpcrt4_io
	00000114    0     wine_rpcrt4_io
	00000130    0     wine_rpcrt4_io
0000004c explorer.exe
	00000050    0     
	00000054    0     
	00000058    0     wine_rpcrt4_server
00000074 svchost.exe
	00000078    0     
	0000008c    0     
	00000094    0     wine_sechost_service
0000007c MicrosoftEdgeUpdate.exe
	00000080    0     
	000000c4    0     wine_threadpool_worker
	000000c8    0     wine_threadpool_waitqueue
	000000cc    0     wine_threadpool_timer_queue
	000000d0    0     
00000098 winedevice.exe
	0000009c    0     
	000000a4    0     
	000000a8    0     wine_sechost_service
	000000ac    0     
	000000b0    0     
	000000b4    0     
	00000124    0     
000000bc winedevice.exe
	000000c0    0     
	000000d8    0     
	000000dc    0     wine_sechost_service
	000000e0    0     
	000000e4    0     
	000000e8    0     
	000000ec    0     
	000000f0    0     
000000f4 plugplay.exe
	000000f8    0     
	00000100    0     
	00000104    0     wine_sechost_service
	00000108    0     wine_rpcrt4_server
0000010c svchost.exe
	00000110    0     
	00000118    0     
	0000011c    0     wine_sechost_service
	00000120    0     
	00000154    0     wine_rpcrt4_server
	00000158    0     wine_rpcrt4_server
00000128 rpcss.exe
	0000012c    0     
	00000134    0     
	00000138    0     wine_sechost_service
	0000013c    0     wine_rpcrt4_server
	00000140    0     wine_rpcrt4_server
	00000144    0     wine_rpcrt4_io
0000016c (D) Z:\media\user\win10\Users\andyp\Downloads\artifact\si-edit.exe
	00000170    0 <== 
	000001cc    0     wine_rpcrt4_server
0000017c vc_redist.x64.exe
	00000180    0     
00000188 vc_redist.x64.exe
	0000018c    0     
	00000194    0     
	000001c0    0     
000001a8 vc_redist.x64.exe
	000001ac    0     
000001b4 vc_redist.x64.exe
	000001b8    0     
	000001c4    0     
	000001c8    0     
000001ec conhost.exe
	000001f0    0     
System information:
    Wine build: wine-8.0.1
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.19.0-41-generic
"

**Comment by itsmattkc** [comment]
> i tried using ubuntu

If you're using Ubuntu, you should probably compile it natively rather than through Wine.

As for the OP, I'll investigate. I don't use Windows regularly and my local Linux build seems fine.

**Comment by itsmattkc** [comment]
Should be fixed now, thanks for reporting

**Comment by Andy4169** [comment]
> > i tried using ubuntu
> 
> If you're using Ubuntu, you should probably compile it natively rather than through Wine.
> 
> As for the OP, I'll investigate. I don't use Windows regularly and my local Linux build seems fine.

i used ubuntu and windows btw

**Comment by A-6-hawk** [comment]
> Should be fixed now, thanks for reporting

Thanks for fixing
